version: 3

vars:
  OUTPUT_DIR: "model_codesearchnet"

tasks:
  clean: "rm -r {{.OUTPUT_DIR}}"
  run-classifier:
    deps: [":venv:create"]
    cmds:
      - >
        {{.VENV_PYTHON}} code/run_classifier.py
        --model_type roberta
        --do_train
        --do_eval
        --eval_all_checkpoints
        --train_file train_codesearchnet_7.json
        --dev_file dev_codesearchnet.json
        --max_seq_length 200
        --per_gpu_train_batch_size 16
        --per_gpu_eval_batch_size 16
        --learning_rate 1e-5
        --num_train_epochs 3
        --gradient_accumulation_steps 1
        --warmup_steps 1000
        --evaluate_during_training
        --data_dir ./data/
        --output_dir {{.OUTPUT_DIR}}
        --encoder_name_or_path microsoft/codebert-base
  dev-run-classifier:
    deps: [":venv:create"]
    cmds:
      - >
        {{.VENV_PYTHON}} code/run_classifier.py
        --model_type roberta
        --do_predict
        --test_file test_webquery.json
        --max_seq_length 200
        --per_gpu_eval_batch_size 2
        --data_dir ./data/
        --output_dir ./model_codesearchnet/checkpoint-best-aver/
        --encoder_name_or_path microsoft/codebert-base
        --pred_model_dir ./model_codesearchnet/checkpoint-last/
        --prediction_file ./evaluator/webquery_predictions.txt